[package]
name = "flipper"
version = "0.1.0"
authors = ["Robert Masen <r@robertmasen.pizza>"]

[dependencies]
robohome_shared = { path = "../shared" }
warp = "0.1"
serde_json = "1"
env_logger = "0.5"
uuid = { version = "0.5", features = ["v4", "serde"] }
log = "0.4"
