[package]
name = "refresher"
version = "0.1.0"
authors = ["Robert Masen <r@robertmasen.pizza>"]
edition = "2018"

[dependencies]
robohome_shared = { path = "../shared" }
reqwest = "0.9"
serde = "1"
serde_derive = "1"
serde_json = "1"
log = "0.4"
pretty_env_logger = "0.3"